### PR TITLE
Liam/testing

### PR DESCRIPTION
**Pull request by niehusst**
Adds integration and controller tests. 
Note: 4 tests should fail; 3 in MenuControllerTest and 1 in CalendarIntegrationTest
The menu controller tests fail because the feature they test is incomplete, or broken (not sure which) and the calendar test fails because of an open bug

### CODE REVIEW

**Comment by niehusst** [comment]
oh, also, test suite may require chrome in order to run/pass

**Comment by GouwarPower** [comment]
Running `rails test` caused the following error: 
.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- Date (LoadError)

Is there something that I'm doing wrong?

**Comment by niehusst** [comment]
> Running `rails test` caused the following error:
> .rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- Date (LoadError)
> 
> Is there something that I'm doing wrong?

maybe its a Linux vs macOS difference? try changing in test_helper.rb the `require 'Date'` to lowercase and see if it fixes it?

**Comment by niehusst** [comment]
also try bundle installing?; I added a new gem

**Comment by GouwarPower** [comment]
Linux strikes again. I had bundled, but changing date to lowercase fixed it. I'll commit the change and you can test if it works for you.

**Pull request merged**
